CREATE DATABASE sparksica;

CREATE TABLE customer(
    customer_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email_id VARCHAR(100) NOT NULL,
    balance_amount NUMERIC(19, 2)
);

CREATE TABLE transactions(
    transactions_id INT GENERATED BY DEFAULT AS IDENTITY(START WITH 10000000 INCREMENT BY 1),
    customer_id INT NOT NULL,
    transfer_amount NUMERIC(8,1),
    transfer_time TIMESTAMP,
    PRIMARY KEY (transactions_id),
    FOREIGN KEY (customer_id) REFERENCES customer(customer_id)
);